# Generated by Django 6.1 on 2026-08-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=2048)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
